### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-formatter#27]
- [ ] check existing API functionality
- [ ] add missing important API functionality
- [ ] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs

**Comment by lnielsen** [comment]
Closed by 323b33895f4f660053c3fa12cb46d9acb425553c
